version: '3.9'

services:
  rs-rest-service:
    env_file: .env
    build:
      context: ./
      args:
        port: ${PORT}
        workdir: ${DOCKER_WORKD_DIR:-/usr/app}
    image: rklepov/rs-rest-service
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - logs:${DOCKER_WORKD_DIR:-/usr/app}/${LOG_DIR:-logs}:rw
      - ./src:${DOCKER_WORKD_DIR:-/usr/app}/src:ro

volumes:
  logs:
