# docker-compose.yml

version: '3.9'

services:
  app:
    build:
      context: ./
      args:
        port: ${PORT}
        workdir: ${DOCKER_WORKD_DIR:-/usr/app}
    image: rklepov/rs-rest-svc-app
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - logs:${DOCKER_WORKD_DIR:-/usr/app}/${LOG_DIR:-logs}:rw
      - ./src:${DOCKER_WORKD_DIR:-/usr/app}/src:ro
    networks:
      - privatenet
    environment:
      PORT: ${PORT}
      ADDR: ${ADDR}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_DIR: ${LOG_DIR}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  db:
    build:
      context: ./db/
    image: rklepov/rs-rest-svc-db
    ports:
      - ${PGPORT}:${PGPORT}
    restart: unless-stopped
    volumes:
      - pgdata:${PGDATA}:rw
    networks:
      - privatenet
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      PGPORT: ${PGPORT}

volumes:
  logs: null
  pgdata: null

networks:
  privatenet:
    driver: bridge
    ipam:
      options: {}
      config:
        - subnet: 172.28.0.0/28

#__EOF__
