version: '3.9'

services:
  app:
    env_file: .env
    build:
      context: ./
      args:
        port: ${PORT}
        workdir: ${DOCKER_WORKD_DIR:-/usr/app}
    image: rklepov/rs-rest-svc-app
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - logs:${DOCKER_WORKD_DIR:-/usr/app}/${LOG_DIR:-logs}:rw
      - ./src:${DOCKER_WORKD_DIR:-/usr/app}/src:ro

  db:
    env_file: .env
    build:
      context: ./db/
    image: rklepov/rs-rest-svc-db
    ports:
      - ${PGPORT}:${PGPORT}


volumes:
  logs:
