version: '3.9'

services:
  rs-rest-service:
    env_file: .env
    build:
      context: ./
      args:
        port: ${PORT}
    image: rklepov/rs-rest-service
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
